name: Fortify Scan

on:
  push:
    branches: [fortify_mob]

jobs:
  fortify:
    runs-on: ubuntu-latest

    container:
      image: fortifydocker/fortify-ci-tools:latest-jdk-17
      env:
        FCLI_DEFAULT_SC_SAST_CLIENT_AUTH_TOKEN: ${{ secrets.FCLI_DEFAULT_SC_SAST_CLIENT_AUTH_TOKEN }}
        FCLI_DEFAULT_SSC_USER: ${{ secrets.FCLI_DEFAULT_SSC_USER }}
        FCLI_DEFAULT_SSC_PASSWORD: ${{ secrets.FCLI_DEFAULT_SSC_PASSWORD }}
        FCLI_DEFAULT_SSC_CI_TOKEN: ${{ secrets.FCLI_DEFAULT_SSC_CI_TOKEN }}
        FCLI_DEFAULT_SSC_URL: ${{ secrets.FCLI_DEFAULT_SSC_URL }}
        SSC_APP_VERSION_ID: ${{ secrets.SSC_APP_VERSION_ID }}
        SC_SAST_SENSOR_VERSION: 24.4

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Login Fortify SSC
        run: |
          echo "Conectando à Fortify Platform"
          fcli ssc session login --url $FCLI_DEFAULT_SSC_URL -u $FCLI_DEFAULT_SSC_USER -p $FCLI_DEFAULT_SSC_PASSWORD -c $FCLI_DEFAULT_SC_SAST_CLIENT_AUTH_TOKEN
      # - name: Empacotamento da aplicação
      #   run: |
      #     echo "Empacotando a aplicação"
      #     scancentral package -bt mvn -o package.zip
      # - name: Enviando a análise
      #   run: |
      #     fcli sc-sast scan start --publish-to=$SSC_APP_VERSION_ID --file=package.zip --store=Id --scan-args -scan
      # - name: Esperando resultado do Scan
      #   run: |
      #     fcli sc-sast scan wait-for ::Id:: --interval=5m
      #     fcli ssc issue count --appversion=$SSC_APP_VERSION_ID
      - name: Baixando o fpr
        run: |
          fcli ssc appversion download-state --include-sources --file app.fpr $SSC_APP_VERSION_ID
      - name: Arquivar FPR
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fpr
          path: app.fpr
      - name: Marcar repositório como seguro para Git
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"
      - name: Analisando com o MOBB
        uses: mobb-dev/action@v1.1
        with:
          report-file: "app.fpr"
          api-key: ${{ secrets.MOBB_API_TOKEN }}
          github-token: ${{ secrets.GH_TOKEN }}
      - name : Logout da ferramenta
        run: |
          fcli ssc session logout  
